---
- name: Install and Configure CloudWatch Agent
  hosts: jenkins
  become: yes

  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Download CloudWatch Agent using wget
      ansible.builtin.command:
        cmd: >
          wget -O /tmp/amazon-cloudwatch-agent.deb
          https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
      args:
        creates: /tmp/amazon-cloudwatch-agent.deb

    - name: Install CloudWatch Agent
      ansible.builtin.apt:
        deb: /tmp/amazon-cloudwatch-agent.deb

    - name: Create CloudWatch Agent config
      ansible.builtin.copy:
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        content: |
          {
            "agent": {
              "metrics_collection_interval": 60,
              "run_as_user": "root"
            },
            "metrics": {
              "append_dimensions": {
                "InstanceId": "${aws:InstanceId}"
              },
              "aggregation_dimensions": [["InstanceId"]],
              "metrics_collected": {
                "cpu": {
                  "measurement": ["cpu_usage_idle", "cpu_usage_iowait"],
                  "metrics_collection_interval": 60,
                  "resources": ["*"]
                },
                "mem": {
                  "measurement": ["mem_used_percent"],
                  "metrics_collection_interval": 60
                }
              }
            }
          }
        mode: '0644'

    - name: Start and Enable CloudWatch Agent
      ansible.builtin.systemd:
        name: amazon-cloudwatch-agent
        state: started
        enabled: yes
